/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyERC20__factory } from "./MyERC20__factory";
export { MyERC721__factory } from "./MyERC721__factory";
export { MyToken__factory } from "./MyToken__factory";
