/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AmountDeriver,
  AmountDeriverInterface,
} from "../../../../seaport/contracts/lib/AmountDeriver";

const _abi = [
  {
    inputs: [],
    name: "InexactFraction",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601357603a908160198239f35b600080fdfe600080fdfea2646970667358221220bd7cf9c766ebaa067299c73a7d089e54cd9dfb9c6e7e43f812f418caf65f925764736f6c63430008110033";

type AmountDeriverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AmountDeriverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AmountDeriver__factory extends ContractFactory {
  constructor(...args: AmountDeriverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AmountDeriver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AmountDeriver__factory {
    return super.connect(runner) as AmountDeriver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AmountDeriverInterface {
    return new Interface(_abi) as AmountDeriverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AmountDeriver {
    return new Contract(address, _abi, runner) as unknown as AmountDeriver;
  }
}
